Repository lxndrblz/forensicsim, pull requests merged in 2024-01, with the labels that each got.

#21 fix: update lisence badge 🏅
  README.md
Labels: documentation

#22 refactor: Replace travis-ci with github action 🐙
  .github/dependabot.yaml
  .github/workflows/release.yaml
  .gitignore
  .travis.yml
  README.md
  main.spec
Labels: enhancement

#24 fix: path of dist/ 🐙
  .github/workflows/release.yaml
Labels: bug

#31 feat: add gh action for build 🐙
  .github/workflows/build.yaml
Labels: enhancement

#35 refactor: replace argparse with click and pyfiglet with const 🪥
  .github/workflows/build.yaml
  main.spec
  requirements.txt
  utils/consts.py
  utils/dump_leveldb.py
  utils/dump_localstorage.py
  utils/dump_sessionstorage.py
  utils/main.py
  utils/populate_skype.py
  utils/populate_teams.py
  utils/populate_teams_2.py
Labels: enhancement

#40 feat: add zip for autopsy to release 🗜️
  .github/workflows/release.yaml
  README.md
  build.bat
Labels: enhancement

#45 refactor!: organize project in source layout to make easily installable 🆕
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  README.md
  main.spec
  pyproject.toml
  requirements.txt
  src/forensicsim/__init__.py
  src/forensicsim/backend.py
  src/forensicsim/consts.py
  src/forensicsim/parser.py
  tools/Forensicsim_Parser.py
  tools/dump_leveldb.py
  tools/dump_localstorage.py
  tools/dump_sessionstorage.py
  tools/main.py
  tools/populate_skype.py
  tools/populate_teams.py
  tools/populate_teams_2.py
Labels: python

#47 chore: bump version number 🐍
  .github/workflows/release.yaml
  CITATION.cff
  src/forensicsim/__init__.py
Labels: dependencies

#55 feat: add code owners file 🥷
  .github/CODEOWNERS
Labels: documentation

#74 fix: resolves Autopsy error when running module
  tools/Forensicsim_Parser.py
Labels: bug
